defmodule Moth.Game.Code do
  @moduledoc """
  Generates human-friendly room codes in WORD-NN format.
  Word list: ~2000 common English words. Code space: ~200,000.
  """

  @words ~w(
    AMBER ARROW ATLAS BADGE BEACH BLAZE BLOOM BRAVE BRICK BROOK
    CANDY CEDAR CHARM CHESS CLIFF CLOUD COBRA CORAL CRANE CREEK
    CROWN DANCE DELTA DREAM DRIFT EAGLE EMBER FAIRY FLAME FLASH
    FORGE FROST GHOST GLEAM GLOBE GRACE GROVE GUARD HAVEN HEART
    IVORY JEWEL KARMA LEMON LIGHT LUNAR MAPLE MARSH MIRTH MOOSE
    NIGHT NOBLE NORTH OCEAN OLIVE ONION ORBIT OTTER PANDA PEARL
    PENNY PERCH PILOT PLUME POLAR PRISM PULSE QUEEN QUEST QUICK
    RAVEN REALM RIDGE RIVER ROBIN ROCKY ROYAL SAFARI SAGE SCOUT
    SHADE SHELL SHORE SMILE SNAKE SOLAR SPARK SPICE SPIKE SPINE
    STAFF STAMP STAND STEAM STEEL STONE STORM SUGAR SUNNY SURGE
    SWIFT SWORD TEMPO THORN TIGER TOPAZ TORCH TOWER TRACK TRAIL
    TRIBE TULIP ULTRA UNITY VALOR VAULT VIGOR VIOLA VIPER VIVID
    WATER WHALE WHEAT WINGS WINTER WITCH WORLD WRATH YACHT YOUTH
    ZEBRA ANCHOR AUTUMN BAMBOO BANNER BASKET BEACON BEETLE BEYOND
    BISHOP BLANKET BLAZER BORDER BOUNCE BRANCH BREEZE BRIDGE BRONZE
    BUCKET BUMBLE BUNNY BUTTER CACTUS CALICO CANDLE CANYON CASTLE
    CHERRY CIRCLE CIRCUS COBALT COFFEE COMEDY COPPER COSMOS COTTON
    COYOTE CRAYON DAGGER DAHLIA DESERT DINNER DONKEY DRAGON EMPIRE
    FALCON FERRET FLOWER FOREST GINGER GLACIER GOLDEN GRAVEL HAMMER
    HARBOR HERMIT HOLLOW HONEY HORNET HUNTER IGLOO ISLAND JACKET
    JAGUAR JUNGLE KITTEN KNIGHT LADDER LANTERN LARIAT LEGEND LIZARD
    MAGNET MANGO MARBLE MEADOW METEOR MINGLE MIRROR MONKEY MOSAIC
    MUFFIN MUSCLE MUSTARD MYSTIC NEBULA NETTLE NIMBLE NUGGET NUTMEG
    ORCHID OSPREY OYSTER PADDLE PALACE PANTHER PARROT PASTEL PEBBLE
    PEPPER PIGEON PLANET PLOVER POCKET PONDER PORTAL POSSUM POTATO
    POWDER PRAIRIE PURPLE PUZZLE PYTHON QUARTZ RABBIT RACOON RADISH
    RANGER RAPIDS RAPTOR RIBBON RIDDLE RIPPLE ROCKET RUBBER RUSTIC
    SADDLE SALMON SANDAL SATURN SCARAB SHADOW SIERRA SILVER SKETCH
    SLIPPER SPIDER SPIRIT SPROUT STITCH STREAM STRIPE SUMMIT SUNSET
    SYLVAN TANGLE TEMPLE TENDER THRONE TIMBER TOUCAN TROPIC TRUFFLE
    TUMBLE TUNNEL TURTLE TUXEDO VELVET VENTURE VIOLET WALRUS WANDER
    WEASEL WHISPER WILLOW WINDOW WINTER WIZARD WONDER ZENITH ZEPHYR
  )

  @max_retries 10

  @doc "Generates a unique room code. Optionally pass a set of existing codes to avoid."
  def generate(excluded \\ MapSet.new()) do
    generate_with_retries(excluded, @max_retries)
  end

  defp generate_with_retries(_excluded, 0) do
    :crypto.strong_rand_bytes(6) |> Base.url_encode64(padding: false) |> String.upcase() |> String.slice(0, 8)
  end

  defp generate_with_retries(excluded, retries) do
    word = Enum.random(@words)
    number = :rand.uniform(100) - 1
    code = "#{word}-#{String.pad_leading(Integer.to_string(number), 2, "0")}"

    if MapSet.member?(excluded, code) do
      generate_with_retries(excluded, retries - 1)
    else
      code
    end
  end

  @doc "Returns the number of available words."
  def word_count, do: length(@words)
end
